### ISSUE TITLE
Integration not showing up in Home Assistant 2021.6

### ISSUE THREAD

**Issue by ficusdragoneta** [tyjtyj/sgnea#4]
Integration does not seem to be loading. No entities are created as viewed from developer tools.
Running on Home Assistant 2021.6.

Used to work in the past.

**Comment by tyjtyj** [comment]
make sure you updated to version 0.1.3

**Comment by ficusdragoneta** [comment]
I'm already on 0.1.3.

I think the API isn't available on NEA website anymore.
https://www.nea.gov.sg/api/WeatherForecast/forecast24hrnowcast2hrs/

**Comment by tyjtyj** [comment]
Mine both 2021.6 and 2021.5 still working 

![image](https://user-images.githubusercontent.com/5368474/121315250-bf516200-c93a-11eb-8584-9bbb346ebd40.png)

**Comment by ficusdragoneta** [comment]
Ooof you're right. Misconfiguration on my part in configuration.yaml.
