### ISSUE TITLE
forecast icons

### ISSUE THREAD

**Issue by seawiid** [tyjtyj/sgnea#5]
is there a way to get this to display forecast icons like the built in weather integration? i'm not sure how you are using it but all i get is text displayed right now

**Comment by tyjtyj** [comment]
The icon come from SGNEA website. Is this temporary or permanent. I check both my setup and both showing icon. 

U can try your access to nea picture. for eg, Cloud icon below link
https://www.nea.gov.sg/assets/images/icons/weather-bg/CL.png

**Comment by seawiid** [comment]
ok i dunno what happened but now its got an icon. does this also give the 5 day forecast, etc? or just the next 2 hours. thanks for working on this btw!

**Comment by tyjtyj** [comment]
The reason for the sensor is to trigger automation when its rains without rain sensor. You can probably use default weather forecast which has more details on next few days forecast.
