### ISSUE TITLE
Many attributes are no longer available

### ISSUE THREAD

**Issue by SeeThisIsMe** [tyjtyj/sgnea#6]
Hi, 
Recently it seems that many of the attributes for this are no longer available. The only available details are the ‘state’ (current weather), and 2 attributes ‘entity_picture’ (weather icon/image) and ‘friendly_name’. None of the other attributes are available anymore, such as '24H Forecast' and 'Temperature High' which I have used in automations.
Thanks
![Capture](https://user-images.githubusercontent.com/53046241/162653070-ba30f455-12b0-4e22-ad13-88afbf781f5c.JPG)

.

**Comment by tyjtyj** [comment]
Patch with latest version.. 

My HASS stuck on 2022.03 due to issue with new version thus this fix is late.

https://github.com/tyjtyj/sgnea/releases/tag/0.1.5
